
services:
  postgres:
    image: postgres:latest
    container_name: lab_postgres
    restart: always
    environment:
      POSTGRES_USER: root 
      POSTGRES_PASSWORD: root 
      POSTGRES_DB: dev-db
    ports:
      - "5432:5432"
    volumes:
      - ./migrations/:/docker-entrypoint-initdb.d/
      - pgdata:/var/lib/postgresql/data 

  redis:
    image: redis:latest
    container_name: lab_redis 
    restart: always
    environment:
      REDIS_PASSWORD: root
    ports:
      - "6379:6379"
    volumes: 
      - redisdata:/data
    
volumes:
  pgdata: {}  
  redisdata: {}

