version: "3.9"

services:
  postgres:
    image: postgres:latest
    container_name: lab_postgres
    restart: always
    environment:
      POSTGRES_USER: root 
      POSTGRES_PASSWORD: root 
      POSTGRES_DB: dev-db
    ports:
      - "5432:5432"
    volumes:
      - ./migrations/:/docker-entrypoint-initdb.d/
      - pgdata:/var/lib/postgresql/data
    networks:
      - researchnet
  redis:
    image: redis:7.2.4-alpine  
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data
    restart: unless-stopped

  rust-backend:
    build:
      context: ./research-labs/rust-backend
      dockerfile: Dockerfile
    depends_on:
      - postgres 
    environment:
      UPLOAD_DIR: /app/uploads
      RUST_HOST: 0.0.0.0
      RUST_PORT: 3009
      DATABASE_URL: postgresql://root:root@postgres/dev-db
    ports:
      - "3009:3009"
    networks:
      - researchnet
    volumes: 
      - ./uploads:/app/uploads  

  rust-gateway:
    build:
      context: ./research-labs/rust-gateway
      dockerfile: Dockerfile
    depends_on:
      - postgres 
    ports:
      - "6188:6188"
    networks:
      - researchnet

  node-backend:
    build:
      context: ./research-labs/backend  
      dockerfile: Dockerfile
    depends_on:
      - postgres 
    environment:
      UPLOAD_DIR: /app/uploads
      DATABASE_URL: postgresql://root:root@postgres/dev-db
    ports:
      - "3005:3005"
    networks:
      - researchnet

  node-chat:
    build:
      context: ./research-labs/chat-service 
      dockerfile: Dockerfile
    depends_on:
      - postgres 
    environment:
      DATABASE_URL: postgresql://root:root@postgres/dev-db
      JWT_SECRET: access
    ports:
      - "3007:3007"
    networks:
      - researchnet

  frontend:
    build:
      context: ./research-labs/frontend
      dockerfile: Dockerfile
    depends_on:
      - rust-backend
      - node-backend
    ports:
      - "3000:3000"  # Next.js default port
    environment:
      UPLOAD_DIR: /app/uploads
      NEXT_PUBLIC_RUST_BACKEND_URL: http://rust-backend:3009
      NEXT_PUBLIC_NODE_BACKEND_URL: http://node-backend:3005
      NEXT_PUBLIC_RUST_GATEWAY_URL: http://rust-gateway:6188
    networks:
      - researchnet

volumes:
  pgdata: {}  
  redisdata: {}

networks:
  researchnet:
    driver: bridge
