[package]
name = "gateway"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = "0.1.88"
pingora =  {version = "0.5.0", features = ["proxy"] }
log = "0.4"
env_logger = "0.10"
tokio = "1.45.1"
http = "1.3.1"
